{% set name = "multitaper" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multitaper-{{ version }}.tar.gz
  sha256: a803f76504d530e439b81693ef957ffb7c2370fcdd7ae81a77832e4758c74362

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - numba

test:
  imports:
    - multitaper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/gaprieto/multitaper
  summary: Multitaper codes translated into Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
